[package]
name = "bincode_derive"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.9"

[dependencies.syn]
version = "1.0.74"
default-features = false
features  = ["parsing", "derive", "proc-macro", "printing"]
